spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
#  data:
#    cassandra:
#      cassandra:
#        keyspace-name: taco_cloud
#        schema-action: recreate
#        local-datacenter: datacenter1
