spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
  data:
    rest:
      base-path: /data-api
  artemis:
    host: localhost
    port: 61616
    user: tacoweb
    password: l3tm31n

taco:
  orders:
    pageSize: 10
