spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
  data:
    rest:
      base-path: /data-api
#  jms:
#    template:
#      default-destination: tacocloud.order.queue
  artemis:
    host: localhost
    port: 61616
    user: tacoweb
    password: l3tm31n
    embedded:
      enabled: false

  kafka:
    template:
      default-topic: tacocloud.orders.topic
    producer:
      bootstrap-servers: localhost:9092
#      keySerializer: org.springframework.kafka.support.serializer.JsonSerializer
#      valueSerializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

taco:
  orders:
    pageSize: 10
